name: Deploy to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo registry
        id: cache-registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
      - name: Cache cargo index
        id: cache-index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index
      - name: Install dependencies
        if: steps.cache-registry.outputs.cache-hit != 'true' || steps.cache-index.outputs.cache-hit != 'true'
        run: |
          (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
          cargo install-update -a
      - name: Build
        run: mdbook build
      - name: Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git switch gh-pages
          ls -aA | grep -v "^\.git$" | xargs rm -r
          git restore --source=master .
          git add *
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -ma "Deploy to GitHub Pages."
          git push origin gh-pages
